name: ganaderia_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Ajustado para mayor compatibilidad

dependencies:
  flutter:
    sdk: flutter

  # --- ICONOS ---
  cupertino_icons: ^1.0.8
  
  # --- UTILIDADES (El Cerebro) ---
  # Para formatear fechas (ej: 15 Feb 2026) - CRÍTICO para tu NewCowScreen
  intl: ^0.19.0 
  
  # Para generar IDs únicos mundiales para cada vaca
  uuid: ^4.3.3

  # --- BASE DE DATOS (La Memoria) ---
  # Base de datos NoSQL súper rápida y offline-first
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  
  # Para encontrar dónde guardar los archivos en el celular
  path_provider: ^2.1.2

  # --- GESTIÓN DE ESTADO ---
  # Para mover datos entre pantallas fácilmente
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

  # --- GENERADORES DE CÓDIGO ---
  # Necesarios para crear la base de datos Isar automáticamente
  build_runner: ^2.4.8
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg